import {
  BookOpenCheck,
  Building2,
  ClipboardCheck,
  ClipboardList,
  Dumbbell,
  Factory,
  BriefcaseBusiness,
  FileClock,
  Shield,
  ShieldCheck,
  ShieldAlert,
  GraduationCap,
  LayoutDashboard,
  Megaphone,
  School2,
  Search,
  Settings2,
  Users2,
} from 'lucide-react'
import type { ModuleCard, NavigationSection } from '../types/resources'

export const navigationSections: NavigationSection[] = [
  {
    label: 'Inti',
    items: [
      { label: 'Dashboard', path: '/dashboard', icon: LayoutDashboard },
      {
        label: 'Kesiswaan',
        path: '/kesiswaan',
        icon: Users2,
        allowedRoleCodes: ['student_affairs'],
        children: [
          { label: 'Students', path: '/student-affairs/students', icon: Users2, allowedRoleCodes: ['student_affairs'] },
          { label: 'Enrollments', path: '/student-affairs/enrollments', icon: School2, allowedRoleCodes: ['student_affairs'] },
          { label: 'Mutations', path: '/student-affairs/mutations', icon: Users2, allowedRoleCodes: ['student_affairs'] },
          { label: 'Graduations', path: '/student-affairs/graduations', icon: GraduationCap, allowedRoleCodes: ['student_affairs'] },
          { label: 'Attendances', path: '/student-affairs/attendances', icon: BookOpenCheck, allowedRoleCodes: ['student_affairs'] },
          { label: 'Discipline', path: '/student-affairs/discipline', icon: ShieldAlert, allowedRoleCodes: ['student_affairs'] },
          { label: 'Extracurricular', path: '/student-affairs/extracurricular', icon: Dumbbell, allowedRoleCodes: ['student_affairs'] },
        ],
      },
      {
        label: 'HUBIM',
        path: '/hubim/companies',
        icon: Building2,
        allowedRoleCodes: ['industry_relations', 'hubim'],
        children: [
          { label: 'Companies', path: '/hubim/companies', icon: Factory, allowedRoleCodes: ['industry_relations', 'hubim'] },
          { label: 'Internships', path: '/hubim/internships', icon: BriefcaseBusiness, allowedRoleCodes: ['industry_relations', 'hubim'] },
          { label: 'Alumni', path: '/hubim/alumni', icon: GraduationCap, allowedRoleCodes: ['industry_relations', 'hubim'] },
          { label: 'Internship Logs', path: '/hubim/internship-logs', icon: ClipboardList, allowedRoleCodes: ['industry_relations', 'hubim'] },
        ],
      },
      { label: 'Pengumuman', path: '/announcements', icon: Megaphone, allowedRoleCodes: ['shared', 'student_affairs', 'academic', 'industry_relations', 'hubim'] },
      { label: 'Cari Siswa', path: '/search-students', icon: Search, allowedRoleCodes: ['shared', 'student_affairs', 'academic', 'industry_relations', 'hubim'] },
      { label: 'Audit Logs', path: '/audit-logs', icon: FileClock, allowedRoleCodes: ['admin'] },
      {
        label: 'Administration',
        path: '/admin/users',
        icon: Shield,
        allowedRoleCodes: ['admin'],
        children: [
          { label: 'Users', path: '/admin/users', icon: Users2, allowedRoleCodes: ['admin'] },
          { label: 'Roles', path: '/admin/roles', icon: Shield, allowedRoleCodes: ['admin'] },
          { label: 'Permissions', path: '/admin/permissions', icon: ShieldCheck, allowedRoleCodes: ['admin'] },
          { label: 'Role Permissions', path: '/admin/role-permissions', icon: ShieldCheck, allowedRoleCodes: ['admin'] },
          { label: 'User Roles', path: '/admin/user-roles', icon: Users2, allowedRoleCodes: ['admin'] },
        ],
      },
    ],
  },
  {
    label: 'Master',
    items: [
      {
        label: 'Master Data',
        path: '/master/academic-years',
        icon: Settings2,
        allowedRoleCodes: ['academic'],
        children: [
          { label: 'Academic Years', path: '/master/academic-years', icon: School2, allowedRoleCodes: ['academic'] },
          { label: 'Semesters', path: '/master/semesters', icon: School2, allowedRoleCodes: ['academic'] },
          { label: 'Departments', path: '/master/departments', icon: Settings2, allowedRoleCodes: ['academic'] },
          { label: 'Grade Levels', path: '/master/grade-levels', icon: Settings2, allowedRoleCodes: ['academic'] },
          { label: 'Classes', path: '/master/classes', icon: Settings2, allowedRoleCodes: ['academic'] },
          { label: 'Rooms', path: '/master/rooms', icon: Settings2, allowedRoleCodes: ['academic'] },
        ],
      },
    ],
  },
  {
    label: 'Academic',
    items: [
      {
        label: 'Academic Menu',
        path: '/academic/teachers',
        icon: GraduationCap,
        allowedRoleCodes: ['academic'],
        children: [
          { label: 'Teachers', path: '/academic/teachers', icon: GraduationCap, allowedRoleCodes: ['academic'] },
          {
            label: 'Homeroom Assignments',
            path: '/academic/homeroom-assignments',
            icon: GraduationCap,
            allowedRoleCodes: ['academic'],
          },
          { label: 'Subjects', path: '/academic/subjects', icon: BookOpenCheck, allowedRoleCodes: ['academic'] },
          { label: 'Schedules', path: '/academic/schedules', icon: BookOpenCheck, allowedRoleCodes: ['academic'] },
          { label: 'Assessment Components', path: '/academic/assessment-components', icon: ClipboardCheck, allowedRoleCodes: ['academic'] },
          { label: 'Student Assessments', path: '/academic/student-assessments', icon: ClipboardCheck, allowedRoleCodes: ['academic'] },
          { label: 'Student Grades', path: '/academic/student-grades', icon: GraduationCap, allowedRoleCodes: ['academic'] },
        ],
      },
    ],
  },
]

export const dashboardCards: ModuleCard[] = [
  {
    title: 'Kurikulum',
    subtitle: 'Jembatan cepat ke teachers, subjects, schedules, dan wali kelas.',
    path: '/academic/teachers',
    accent: 'linear-gradient(135deg, #1ac4d6, #4ba8ff)',
    icon: BookOpenCheck,
    chips: ['Teachers', 'Subjects', 'Schedules'],
    allowedRoleCodes: ['academic'],
  },
  {
    title: 'Kesiswaan',
    subtitle: 'Gerbang cepat ke data siswa inti yang nanti menopang enrollment, absensi, dan disiplin.',
    path: '/kesiswaan',
    accent: 'linear-gradient(135deg, #4ba8ff, #87c6ff)',
    icon: Users2,
    chips: ['Siswa', 'Absensi', 'Disiplin'],
    allowedRoleCodes: ['student_affairs'],
  },
  {
    title: 'HUBIM',
    subtitle: 'Tempat untuk perusahaan, prakerin, dan alumni saat modulnya aktif.',
    path: '/hubim',
    accent: 'linear-gradient(135deg, #60c14c, #99da5f)',
    icon: Building2,
    chips: ['Perusahaan', 'Prakerin', 'Alumni'],
    allowedRoleCodes: ['industry_relations', 'hubim'],
  },
  {
    title: 'Pengaturan',
    subtitle: 'Master data inti seperti tahun ajaran, jurusan, tingkat, kelas, dan ruang.',
    path: '/master/academic-years',
    accent: 'linear-gradient(135deg, #ff6b5b, #ff986d)',
    icon: Settings2,
    chips: ['Master Data', 'Academic Years', 'Classes'],
    allowedRoleCodes: ['academic'],
  },
  {
    title: 'Pengumuman',
    subtitle: 'Slot untuk pengumuman lintas unit dan komunikasi terarah.',
    path: '/announcements',
    accent: 'linear-gradient(135deg, #ff986d, #ffb648)',
    icon: Megaphone,
    chips: ['Broadcast', 'Role Targeting'],
  },
  {
    title: 'Cari Siswa',
    subtitle: 'Kelak akan menjadi agregator biodata, kelas, nilai, dan riwayat siswa.',
    path: '/search-students',
    accent: 'linear-gradient(135deg, #4ba8ff, #8dd0ff)',
    icon: Search,
    chips: ['Global Search', 'Cross Module'],
  },
  {
    title: 'Audit Logs',
    subtitle: 'Pantau seluruh aktivitas sistem yang tercatat untuk keperluan audit dan keamanan.',
    path: '/audit-logs',
    accent: 'linear-gradient(135deg, #8b5cf6, #a78bfa)',
    icon: FileClock,
    chips: ['System', 'Activity'],
    allowedRoleCodes: ['admin'],
  },
  {
    title: 'Administration',
    subtitle: 'Kelola user, role, dan permission untuk mengatur hak akses seluruh pengguna.',
    path: '/admin/users',
    accent: 'linear-gradient(135deg, #6366f1, #818cf8)',
    icon: Shield,
    chips: ['Users', 'Roles', 'Permissions'],
    allowedRoleCodes: ['admin'],
  },
]
